### ISSUE TITLE
API doesn't show anything

### ISSUE THREAD

**Issue by Gidro76** [ghaberek/omada-api#10]
Hello. Is your code suitable for use on version 5.5.6?
When calling device.py I get the following

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "devices.py", line 83, in <module>
    main()
  File "devices.py", line 70, in main
    omada.login()
  File "/home/local/Документы/omada-api-main/omada/omada.py", line 244, in login
    self.currentUser = self.getCurrentUser()
  File "/home/local/Документы/omada-api-main/omada/omada.py", line 263, in getCurrentUser
    return self.get( '/users/current' )
  File "/home/local/Документы/omada-api-main/omada/omada.py", line 163, in get
    json = response.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    
    <base href="/" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=1300,initial-scale=1,minimal-ui"/>
    <link rel="shortcut icon" href="favicon.ico"/>

    <link rel="stylesheet" href="theme/lib/css/jquery-8d5462339d.Jcrop.css">
    <link rel="stylesheet" href="theme/lib/css/spectrum-db1edfecae.css">
    <link rel="stylesheet" href="theme/css/su-3d58729bd2.css">
    <title id="title">Omada Controller</title>
    <noscript>
        <meta http-equiv="refresh" content="0; url=error.html"/>
    </noscript>
</head>

<body>
<div id="main-container" class="m-b-0"></div>
<canvas id="canvas-test"></canvas>
<script type="text/javascript" src="js/libs/polyfill-6926951583.min.js"></script>
<script type="text/javascript" src="js/libs/g6-75b82cdd1d.min.js" async></script>
<script type="text/javascript" src="js/libs/jquery-4cb8672160.min.js"></script>
<script type="text/javascript" src="js/libs/jquery-16e37f8666.ui.min.js"></script>
<script type="text/javascript" src="js/libs/sockjs-e2b1fc0be3.min.js"></script>
<script type="text/javascript" src="js/libs/stomp-51779f8e6c.min.js"></script>

<script type="text/javascript" src="js/libs/resize-observer-efda88a98d.min.js"></script>
<script type="text/javascript" src="js/libs/spectrum-b2a4615880.min.js"></script>
<script type="text/javascript" src="js/libs/jquery-29e923ff33.Jcrop.min.js"></script>
<script type="text/javascript" src="js/libs/jquery-fc6a4a4eb5.cookie.min.js"></script>
<script type="text/javascript" src="js/libs/perfect-scrollbar-85fff207d9.min.js"></script>
<script type="text/javascript" src="js/libs/lottie-748e37b680.min.js"></script>
<script type="text/javascript" src="js/libs/cryptoJS-242f7a6460.min.js"></script>
<script type="text/javascript" src="js/libs/moment-761502841c.min.js"></script>
<script type="text/javascript" src="js/libs/moment-timezone-with-data-5c8ed7bc8a.min.js"></script>
<script type="text/javascript" src="js/libs/json2html-8826f30caf.min.js"></script>
<script type="text/javascript" src="js/su/su-08cc8d9f61.js"></script>
<script type="text/javascript">
    $.su.language = new $.su.Language();
    var canvas = document.getElementById("canvas-test");
    try {
        canvas.getContext("2d");
        document.body.removeChild(canvas);
    } catch (e) {
        location.href = "./error.html";
    }
    var WebSocketsExist = !!window.WebSocket;
    if (!WebSocketsExist) {
        location.href = "./error.html";
    }
</script>

<script type="text/javascript" src="js/su/service-b941b02bda.js"></script>

<script type="text/javascript" src="js/su/data-26aadb7101.js"></script>

<script type="text/javascript" src="js/su/widget-cf4f61ec0f.js"></script>

<script type="text/javascript" src="js/su/form-55bf09c22e.js"></script>

<script type="text/javascript" src="js/su/manager-0412ba783a.js"></script>

<script type="text/javascript" src="js/su/dataBind-c7018623df.js"></script>

<script type="text/javascript" src="js/su/application-cd135da3c4.js"></script>

<script type="text/javascript" src="js/app/app-c44cff8888.js"></script>

<script type="text/javascript">
    $(document).ready(function(e){
        App = new $.su.App();
        App.setContainer("main-container");
        App.init().done(function(){
            App.launch();
        });
    });
</script>
</body>
</html>
: 0

**Comment by ghaberek** [comment]
This was fixed by PR #5. I am using this with version 5.7.4.
