### ISSUE TITLE
Discussion: Omada API Information

### ISSUE THREAD

**Issue by arrmo** [ghaberek/omada-api#17]
Sorry, not sure how to raise a discussion here, vs. issue. This is not a bug! That's why I put Discussion in the title.

Just looking for the API information - perhaps provide a link, or better yet ... add the document to your source?

Thanks!

**Comment by ghaberek** [comment]
Historically I've found it difficult to track down any reliable first-party information on the API. I found the best source was usually the web console itself, where I would monitor the requests using Chrome or Firefox developer tools. However, it looks like TP-Link have been doing better lately, with [this thread](https://community.tp-link.com/en/business/forum/topic/590430) from April. I've added some links to this and others to the README.

**Comment by arrmo** [comment]
Got it, thanks!!
