### ISSUE TITLE
Release to PyPi?

### ISSUE THREAD

**Issue by AshtonKem** [ghaberek/omada-api#2]
I just found this, and I was going to use it for a Home Assistant integration. Any chance you can or were planning to release it to PyPi eventually? That makes my life much easier if I can just add it to a manifest file.

**Comment by AshtonKem** [comment]
I believe that the client code already here is sufficient. My only requirements are the ability to list currently connected clients, which I think this can do now.

But I'm not in a huge hurry, this is square in the "it would be nice" camp for me, so if it you want to take a few weeks to polish this up before release then that's no biggie to me.

**Comment by michaelarnauts** [comment]
@AshtonKem Do you have any progress somewhere? I assume you want to use this to query the omada controller so you can create device_trackers for all connected devices?

When using multiple AP's, this could even have the benefit do so some coarse location detection of what part of the house somebody is?
