### ISSUE TITLE
Syntax Error for future-fstrings

### ISSUE THREAD

**Issue by Mssekibaala** [ghaberek/omada-api#7]
When I try to run led.py or clients.py etc I get an error:
"File "led.py", line 1
SyntaxError: encoding problem: future_fstrings"

**Comment by mheath** [comment]
Are you using Python 3 and have you installed `future_fstrings`. Running `pip -r requirements.txt` will install `future_fstrings`.

**Comment by warllo54** [comment]
I am also running into the same error:

`SyntaxError: unknown encoding: future_fstrings`

pip install reports:
`py -m pip install future_fstrings
Requirement already satisfied: future_fstrings in c:\users\lloyd\appdata\local\programs\python\python310\lib\site-packages\future_fstrings-1.2.0-py3.10.egg (1.2.0)`

**Comment by ghaberek** [comment]
Moving forward I will remove use of `future_fstrings` so you will need to use Python 3.6 or higher.
